version: "3.7"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    container_name: sbarp
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8000:1323"
    networks:
      - backend
  database:
    image: postgres:14.5-alpine
    container_name: dbarp
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9002:5432"
    networks:
      - backend
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
networks:
  backend: